- name: Copy mkinitcpio.conf
  ansible.builtin.template:
    src: mkinitcpio.conf.j2
    dest: /etc/mkinitcpio.conf
    mode: '0644'

- name: Retrieve Linux version
  ansible.builtin.command: ls -1 /lib/modules
  register: linux_version
  changed_when: false

- name: Prepare kernel directory
  ansible.builtin.file:
    path: /boot/{{ ansible_machine_id }}
    state: directory
    mode: '0755'

- name: Install kernel to boot
  ansible.builtin.command: kernel-install add {{ linux_version.stdout }} /boot/vmlinuz-linux-lts
  changed_when: true

- name: Copy loader.conf
  ansible.builtin.template:
    src: entry.conf.j2
    dest: /boot/loader/entries/{{ ansible_machine_id }}-{{ linux_version.stdout }}.conf
    mode: '0644'

- name: Create pacman hook directory
  ansible.builtin.file:
    path: /etc/pacman.d/hooks
    state: directory
    mode: '0755'

- name: Copy pacman hook
  ansible.builtin.copy:
    src: kernel.hook
    dest: /etc/pacman.d/hooks/kernel.hook
    mode: '0644'
