- name: Install packages
  become: true
  community.general.pacman:
    name:
      - zsh
      - tmux

- name: Install Oh-My-Zsh
  ansible.builtin.command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh/