- name: Setup
  hosts: all
  vars:
    ansible_user: '{{ unix_username }}'
    ansible_ssh_pass: '{{ unix_password }}'
  roles:
    - role: aur
    - role: browser
    - role: cli
    - role: dev
    - role: display
    - role: dotfiles
    - role: editor
    - role: font
    - role: git
    - role: misc
    - role: notification
    - role: rust
    - role: sound
    - role: term
    - role: ops

- name: Disable ssh
  hosts: all
  vars:
    ansible_user: '{{ unix_username }}'
    ansible_ssh_pass: '{{ unix_password }}'
  become: true
  tasks:
    - name: Disable ssh systemd services
      ansible.builtin.systemd:
        name: sshd
        enabled: false
