- name: Install packages
  become: yes
  pacman:
    name:
      - awesome-terminal-fonts
      - ttf-dejavu
      - ttf-droid
      - ttf-nerd-fonts-symbols-common
      - ttf-roboto-mono
      - noto-fonts-cjk
      - noto-fonts-emoji

# This because of extensive use of the --print-format :
# https://docs.ansible.com/ansible/latest/collections/community/general/pacman_module.html#parameter-executable
- name: Install ttf-ubraille AUR package
  shell: paru -Syu --noconfirm --nouseask ttf-ubraille

- name: Create fontconfig directory
  file:
    path: ~/.config/fontconfig/
    state: directory

- name: Copy fonts.conf
  copy:
    src: fonts.conf
    dest: ~/.config/fontconfig/fonts.conf
