ansible_python_interpreter: /usr/bin/python3

# LUKS crypted partition password
# crypt_passphrase: password

# User credentials
unix_username: lapoule
unix_password: XXXXXXXX

# Misc
machine_hostname: archlinux-station
locale: en_US.UTF-8
timezone: Europe/Paris
# keymap: fr
git_user_name: ElieLP
git_user_email: elie973@gmail.com
