- name: Install editor packages
  become: true
  community.general.pacman:
    name:
      - vi
      - vim
      - code

- name: Copy vim bash_profile
  ansible.builtin.copy:
    src: vim.bash_profile
    dest: ~/.bash_profile.d/
    mode: '644'

- name: Copy vim bashrc
  ansible.builtin.copy:
    src: vim.bashrc
    dest: ~/.bashrc.d/
    mode: '644'
