theme = "solarized-dark"
icons = "awesome"
icons_format = " <span font_family='NotoSans Nerd Font'>{icon}</span> "

[[block]]
block = "custom"
command = "echo -n '\uf109 '; cat /etc/hostname"
interval = "once"

[[block]]
block = "custom"
command = "echo \uf17c  Linux `uname -r`"
interval = "once"

[[block]]
block = "pacman"
interval = 600
format = "{both} updates available"
format_singular = "{both} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux |linux-lts|linux-zen)"
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
aur_command = "paru -Qua"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
clickable = false
format_mem = "{mem_used_percents} ({mem_used}/{mem_total})"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
format = "{icon} {used}/{total}"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
format = "{ip}{speed_down}{speed_up}"
interval = 5

[[block]]
block = "backlight"

[[block]]
block = "sound"
driver = "pulseaudio"
max_vol = 120

[[block]]
block = "custom"
interval = "once"
json = true
command = "echo '{\"icon\":\"cogs\", \"state\":\"Info\", \"text\": \"\"}'"
on_click = "pavucontrol"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d %b %R"
