- name: Install misc packages
  become: yes
  pacman:
    name:
      - nasm

# This because of extensive use of the --print-format :
# https://docs.ansible.com/ansible/latest/collections/community/general/pacman_module.html#parameter-executable
- name: Install gef-git AUR package
  shell: paru -Syu --noconfirm --nouseask gef-git
