- name: Install misc packages
  become: true
  community.general.pacman:
    name:
      - nasm

# This because of extensive use of the --print-format :
# https://docs.ansible.com/ansible/latest/collections/community/general/pacman_module.html#parameter-executable
- name: Install gef-git AUR package
  ansible.builtin.command: paru -Syu --noconfirm --nouseask gef-git
  args:
    creates: /usr/share/gef/gef.py
  # TODO add:
  #   echo source ~/.gdbinit-gef.py >> ~/.gdbinit
  # to .gdbinit

- name: Copy .gdbinit
  ansible.builtin.copy:
    src: .gdbinit
    dest: ~/
    mode: '0644'
