- name: Copy makepkg configuration
  become: true
  ansible.builtin.copy:
    src: makepkg.conf
    dest: /etc/
    mode: '0644'

- name: Install fakeroot packages
  become: true
  community.general.pacman:
    name:
      - fakeroot
      - pkg-config


- name: Clone paru repository
  ansible.builtin.git:
    repo: https://aur.archlinux.org/paru.git
    dest: ~/.local/share/src/paru
  tags:
    - skip_ansible_lint # check latest version of git repository

- name: Make paru
  ansible.builtin.command: makepkg -si --noconfirm
  args:
    chdir: ~/.local/share/src/paru
    creates: /usr/bin/paru
  ignore_errors: '{{ ansible_check_mode }}'
