- name: Install rustup
  become: true
  community.general.pacman:
    name:
      - rustup
      - base-devel

- name: Setup rust
  ansible.builtin.command: rustup default stable
  args:
    creates: /usr/bin/rustc

- name: Copy rust bash_profile
  ansible.builtin.copy:
    src: rust.bash_profile
    dest: ~/.bash_profile.d/
    mode: '644'
