- name: Install i3 packages
  become: true
  community.general.pacman:
    name:
      - i3-wm
      - i3status-rust
      - i3lock
      - xss-lock
      - rofi

- name: Create i3 config directory
  ansible.builtin.file:
    path: ~/.config/i3
    state: directory
    mode: '0755'

- name: Copy i3 config
  ansible.builtin.template:
    src: 'i3/config.j2'
    dest: ~/.config/i3/config
    mode: '0644'

- name: Copy i3 brightness binary
  ansible.builtin.copy:
    src: 'i3/brightness.sh'
    dest: ~/.config/i3/
    mode: '0755'

- name: Copy i3 volume binary
  ansible.builtin.copy:
    src: 'i3/volume.sh'
    dest: ~/.config/i3/
    mode: '0755'

- name: Create i3status-rust config directory
  ansible.builtin.file:
    path: ~/.config/i3status-rust
    state: directory
    mode: '0755'

- name: Copy i3status-rust config
  ansible.builtin.template:
    src: 'i3status-rust/config.toml.j2'
    dest: ~/.config/i3status-rust/config.toml
    mode: '0644'

- name: Copy wallpaper
  ansible.builtin.copy:
    src: linux.png
    dest: ~/Pictures/Wallpapers/
    mode: '0644'
