- name: Install misc
  become: yes
  pacman:
    name:
      - brightnessctl
      - feh
      - thunar
      - file-roller
      - vlc

- name: Create Screenshots directory
  file:
    path: ~/Pictures/Screenshots
