- name: Install misc
  become: true
  community.general.pacman:
    name:
      - brightnessctl
      - feh
      - maim
      - xdotool
      - thunar
      - file-roller
      - vlc

- name: Create Screenshots directory
  ansible.builtin.file:
    path: ~/Pictures/Screenshots
    state: directory
    mode: '0755'
