- name: Install X
  become: yes
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
      - autorandr

- name: Copy .xinitrc
  template:
    src: .xinitrc.j2
    dest: ~/.xinitrc
