- name: Install X
  become: true
  community.general.pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
      - autorandr

- name: Copy .xinitrc
  ansible.builtin.copy:
    src: xorg/.xinitrc
    dest: ~/
    mode: '0644'

- name: Copy synaptics Xorg conf
  become: true
  ansible.builtin.copy:
    src: xorg/synaptics.conf
    dest: /etc/X11/xorg.conf.d/70-synaptics.conf
    mode: '0644'
