- name: Install git
  become: true
  community.general.pacman:
    name: git

- name: Create git config directory
  ansible.builtin.file:
    path: ~/.config/git
    state: directory
    mode: '755'

- name: Copy git config
  ansible.builtin.template:
    src: config.j2
    dest: ~/.config/git/config
    mode: '644'
