- name: Create user
  ansible.builtin.user:
    name: '{{ unix_username }}'
    password: '{{ unix_password | password_hash("sha512") }}'
    groups: adm,disk,wheel,audio,video,users
    append: true

- name: Copy sudoers conf
  ansible.builtin.copy:
    src: sudoers
    dest: /etc/sudoers.d/wheel
    mode: '0644'
